### ISSUE TITLE
Alpha-channel doesn't work

### ISSUE THREAD

**Issue by kvloginov** [dmamylin/vsrat2d#1]
I tried to draw a circle with Color having alpha channel == 0, but i still see this circle!
Make it transparent for me, please!

What I see:
![image](https://user-images.githubusercontent.com/3582585/202572007-3fb99b79-ae05-4ef7-b6a5-809e99627525.png)

What I want to see:
![image](https://user-images.githubusercontent.com/3582585/202572098-f867cd96-51ad-4345-af13-d8f8b1579822.png)

My code:
```java
 var pos = new Point2D(windowWidth * 0.5f, windowHeight * 0.5f);
        var color = new Color(1f, 1f, 1f, 0f);
        ctx.screen().drawCircle(pos, 100, new Paint(color, true));
```

**Comment by dmamylin** [comment]
Looks like a weird bug, but i dunno if can help! But I'll try, ok.

**Comment by dmamylin** [comment]
Should work since version-1.2.4.
